-- Customers table
create table customers (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  phone varchar(32),
  email varchar(100)
);

-- Accounts table
create table accounts (
  id bigint generated by default as identity primary key,
  customer_id bigint not null,
  number varchar(32) not null unique,
  currency varchar(3) not null,
  balance numeric(19,2) not null default 0,
  status varchar(16) not null default 'ACTIVE',
  constraint fk_account_customer foreign key (customer_id) references customers(id)
);

-- Transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  account_id bigint not null,
  type varchar(10) not null,           -- 'DEBIT' or 'CREDIT'
  amount numeric(19,2) not null,
  currency char(3) not null,
  reference varchar(128),
  counterparty varchar(64),
  created_at timestamp not null default current_timestamp,
  constraint fk_txn_account foreign key (account_id) references accounts(id)
);

create index idx_txn_account_created on transactions(account_id, created_at);
